### ISSUE TITLE
Upgrade for angular 17 and dependency review

### ISSUE THREAD

**Issue by POFerro** [danielmoncada/date-time-picker-moment-adapter#16]
Hi :),

Is it possible to upgrade the dependencies to support angular 17?
In the meantime this module has dependencies declared for @angular/common and @angular/core and @angular/cdk are these necessary? The only explicit dependency I see in code is of @angular/core. Am I missing something?

Thanks and congrats for keeping this nice component alive :).
POFerro

**Comment by danielmoncada** [comment]
@POFerro 4.0.0 has now been released, which supports ng 17.

you're right about the dependencies.. mind making a PR to remove those? otherwise I can when I have time to get to it. lmk

**Comment by POFerro** [comment]
Thanks @danielmoncada , I didn't realize there was a new version :).
I submited a PR for the dependencies.

Thanks and best regards
POFerro
