### ISSUE TITLE
Upgrade to Angular 18

### ISSUE THREAD

**Issue by GKersten** [danielmoncada/date-time-picker-moment-adapter#19]
Hi,

Would be great if this package could be updated to support Angular 18.

Thanks for all the efforts!

**Comment by richagain** [comment]
I have created this PR: https://github.com/danielmoncada/date-time-picker-moment-adapter/pull/20

Just need to merge it.

**Comment by danielmoncada** [comment]
@GKersten the latest package on npm, v18 was updated about a month ago https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker

**Comment by danielmoncada** [comment]
published: https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker-moment-adapter
