### ISSUE TITLE
Add OWL_MOMENT_DATE_TIME_ADAPTER_OPTIONS to public_api

### ISSUE THREAD

**Issue by neodescis** [danielmoncada/date-time-picker-moment-adapter#2]
Can we add OWL_MOMENT_DATE_TIME_ADAPTER_OPTIONS injection token to the list of exports in public_api? Currently there doesn't seem to be a way for me to import the injection token so I can set the useUtc option for the adapter.

**Comment by danielmoncada** [comment]
yeah, i'll do that.. hopefully i can get to it this week.

**Comment by danielmoncada** [comment]
Fixed in https://github.com/danielmoncada/date-time-picker-moment-adapter/pull/3/

Updated version to 1.1.0

**Comment by neodescis** [comment]
Thank you very much!
