### ISSUE TITLE
OWL_DATE_TIME_FORMATS not working on angular 13

### ISSUE THREAD

**Issue by quan1997ap** [danielmoncada/date-time-picker-moment-adapter#6]
I'm setting OWL_DATE_TIME_FORMATS  with  { provide: OWL_DATE_TIME_LOCALE, useValue: 'vi-VN' } but it not working
I try your demo https://stackblitz.com/edit/angular-ae6mv3?file=app%2Fapp.module.ts  but it only run on angular 5. 
How can i fix this. 

Thanks you

**Comment by danielmoncada** [comment]
this is not for angular 13. https://github.com/danielmoncada/date-time-picker supports 14 and above
